service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60
    memorySize: 128
